server:
  port: 8083
fts:
  db:
    database: fts-product
    host: 47.111.117.150
    pw: SQLPASSWORD
  swagger:
    title: WiseInvest产品服务接口文档
    description: WiseInvest产品服务接口文档
    package: com.plugin.vivien.product.controller