server:
  port: 8081
fts:
  db:
    database: fts-account
    host: 47.111.117.150
    pw: SQLPASSWORD
  swagger:
    title: WiseInvest账户服务接口文档
    description: WiseInvest账户服务接口文档
    package: com.plugin.vivien.account.controller